language: node_js

node_js:
  - '6'
  - '8'

notifications:
  email: false

addons:
  code_climate:
    repo_token:
      secure: GITRPEJleeEL+21jv7z+dT45vvzjyHRVedkRtB2QAj0XQgRBoUD6ApdKKytjdA5ChvWDQI+rdxWI4ayZBeyuCf5eMUBr2lVhtCQZ9LqYBqTYqKABHIB5jYfx7nV9ZWsbpi1p1tW7TJLReP/EiwVNqReFBq0y87ouVWTPTJFWBRnmT5UxBghkI/xnXnLz7/WAfdN57Dc2AcnqvMQyDGW1Vc8qZJ+CHnLd9XoyKBgBCoBrcuxsNX9LeXBrQ3HXvglPt4jZYMq4WxbfPXklrc/3UST/9O7GebPUiRTCwMP56fNTyUYvcd33U59hMamLRqROa8CrRwRVN7yeVIu7G93gMMDBJsR1EjeLMowuVa84dpwmCIrF3OtBSx+2hlkk8ba5QFRDoEtbH/m9n2ZHIh5s4hd5b4NWI53Hi0SUghxHfh2zTxJjr2tAQ25ShVOQzkrnL+ouOk80G+gylgVpEIRAg1aIS0cMkbxbzGX+j/zhcvOSERvM73dZzQOF8SJ4ihKtF9e+IV+sKuiJxY7ZMYxOf/Dqt+tH1p0nbQQsKVqLoVFREu3ZF2AUzxk9UzEfV+vIyFLqfMTeecjUUg+a0X1hxKVI6MSqT3pg9PN97XCq+JdKCR5mdDmDIZ7jjnHkP7Zgrgn0sldjYY5d2u9N3+5YrORAcF024LNwgyha+qu2hIs=
